### PR TITLE
Fix compilation with GHC 8

### PR DESCRIPTION
**Pull request by arybczak**

### CODE REVIEW

**Comment by adamgundry** [comment]
Thanks for this. I believe the Travis failures are because `binary-serialise-cbor` has moved on a bit, and we aren't pinned to a specific commit. Probably the easiest fix is to add `git checkout <commit>` after the `git clone` in `.travis.yml`. Please could you try this?

I'd do it but I'm not sure which `binary-serialise-cbor` commit you are using with GHC 8; my local setup has `05a7ebf8a2e1af0feb61bc85b828a712e95762e8` but IIRC that predates GHC 8 and so may or may not be compatible.

It will be great when `binary-serialise-cbor` gets an official release and we can switch to that...

**Comment by arybczak** [comment]
I'm using 0.1.1.0.1 from Iris Connect hackage, I'm not sure what commit is tha. I see the situation is quite messy - should api-tools be updated to work with master branch of binary-serialize-cbor?

**Comment by adamgundry** [comment]
I think that apart from the changed version number, 0.1.1.0.1 is the commit I mentioned before (https://github.com/well-typed/binary-serialise-cbor/commit/05a7ebf8a2e1af0feb61bc85b828a712e95762e8). So we should try pinning that one in the CI to start with.

I'm inclined to wait until `binary-serialise-cbor` gets an official release, then update `api-tools` to be compatible with it.

**Comment by arybczak** [comment]
I made a few changes and checks finally passed 👍

**Pull request merged**
